import { test, expect } from '@playwright/test';

test('Generated by CodeGen', async ({ page }) => {
  await page.goto('https://aslamhabeeb.netlify.app/');
  await page.getByRole('link', { name: 'About' }).click();
  await page.getByRole('link', { name: 'Experience' }).click();
  await page.getByRole('link', { name: 'Experience' }).click();
  await page.getByRole('link', { name: 'Skills' }).click();
  await page.getByRole('link', { name: 'Skills' }).click();
  await page.getByRole('link', { name: 'Contact' }).dblclick();
  await page.getByRole('link', { name: 'Contact' }).dblclick();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('Ash');
  await page.getByRole('textbox', { name: 'Email' }).dblclick();
  await page.getByRole('textbox', { name: 'Email' }).fill('dream@gmail.com');
  await page.getByRole('textbox', { name: 'Subject' }).click();
  await page.getByRole('textbox', { name: 'Subject' }).fill('Assets ');
  await page.getByRole('textbox', { name: 'Message' }).dblclick();
  await page.getByRole('textbox', { name: 'Message' }).fill('Assets have aquired');
  await page.getByRole('button', { name: 'Send Message' }).click();
  await page.getByRole('contentinfo').getByRole('button').click();
  await page.getByRole('button', { name: 'Explore My Work' }).click();
});